name: ARGOCD

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Agent selection string.'
        required: false
        default: 'ubuntu-latest'
        type: string
      tag:
        description: 'Semver Tag'
        required: false
        type: string
    secrets:
      ARGOCD_PAT:
        required: true

jobs:
  deploy:
    name: 'ArgoCD'
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout image version in argocd
        uses: actions/checkout@master
        with:
          repository: wer1hub/argocd
          token: ${{ secrets.ARGOCD_PAT }}

      - name: Update image version
        run: |
          sed -i "s|976284867583.dkr.ecr.eu-west-1.amazonaws.com/graph:.*|976284867583.dkr.ecr.eu-west-1.amazonaws.com/graph:${{ inputs.tag }}|" argocd/dev/apps/graph-private/graph-private.yaml

      - name: Commit updated image version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "support@wer1.ai"
          git add argocd/dev/apps/graph-private/graph-private.yaml
          git commit -m "Update image version to ${{ inputs.tag }}"
          git push
